import express from "express";
import errorMiddleware from "./middleware/error.Middleware.js";
import authRouter from "./routes/auth.routes.js";
import cookieParser from "cookie-parser";
import accountRouter from "./routes/account.routes.js";
import transactionRouter from "./routes/transaction.routes.js";
const app = express();
app.use(express.json());
app.use(cookieParser());
app.use("/api/auth", authRouter);
app.use("/api/account", accountRouter);
app.use("/api/transaction", transactionRouter);
app.use(errorMiddleware);
export default app;
